#cloud-config
disable_root: true
ssh_pwauth: false
users:
  - name: "{{ user }}"
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - "{{ public_ssh_key }}"
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
  - 'HOME=/home/{{ user }} su {{ user }} sh -c "$(curl -LsSf https://astral.sh/uv/install.sh)"'
