---
- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: "{{ docker_keyring }}"
    state: present

- name: Add Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_keyring }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce

- name: Get users
  ansible.builtin.shell:
    cmd: ls /home | xargs
  register: users

- name: Add users to 'docker' group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ users.stdout.split() }}"
